### ISSUE TITLE
width resize on initial render with vuetify navigation drawer 

### ISSUE THREAD

**Issue by waspinator** [apexcharts/vue-apexcharts#125]
Thanks for all your work on this great charts library and vue wrapper.

When adding a chart to a vuetify app with a navigation drawer, the chart's width seems to ignore the drawer and goes past the page. After the drawer is closed and opened it looks right.

https://codepen.io/waspinator/pen/XLOBar

**Comment by catsby91** [comment]
agree, have the same issue

**Comment by catsby91** [comment]
Hello everyone. This style solves my problem. However, it would be great to handle it without disabling any animations.
```
<v-content style="transition: none !important">
      <router-view></router-view>
 </v-content>
```

**Comment by consuman** [comment]
I have this issue too, in a NUXTjs project. On initial pageload its a wrong width, but any resize or route change fixes it.

But great work though! Love Apex!

**Comment by wimil** [comment]
agree, have the same issue ....
im using nuxt proyect

**Comment by giselecpferreira** [comment]
I'm using nuxt. I solved it adding a <v-lazy> before Apex Graphic component, It's happening to me because the navigation drawer is loading after the chart and the graphic size was load base on the initial page size (before the navigation drawer open). I think you can solve this too putting a load component into the graphic area.

**Comment by ifui** [comment]
uh...look this a bad trouble
same have
