### ISSUE TITLE
Update tooltip Vue Chart

### ISSUE THREAD

**Issue by kylawamg** [apexcharts/vue-apexcharts#187]
Hi! 

Im trying to achieve a change in the tooltip's custom template but when I update tooltip.custom property with other function the tooltip not change with the new template. 

Also, Is there any way to add external data from component to tooltip custom template?,How can I access to the component context?

Thank you so much in advance.

**Comment by matia-gov** [comment]
This might be helpful to you -- in order to access the component's data within the chart options, you need to use an arrow function. If I understand correctly, it's because you need to access the global 'this' object, and since arrow functions don't bind their own 'this', but inherit it from their parent scope, you can now use the component's data. 

For me it looked something like this:

` tooltip: {
              y: {
                formatter: (val, obj) => {
                   return this.data[obj.dataPointIndex];
                },
            },`
