### ISSUE TITLE
Total in a pie chart

### ISSUE THREAD

**Issue by Amosss** [apexcharts/vue-apexcharts#197]
Hi

I'm new to apexcharts and I'm still learning its so many options and features.

I asked this question on apexcharts: https://github.com/apexcharts/apexcharts.js/issues/1237 only to realize there's a github for vue-apexcharts. A fix there is also a fix here? If so, how/when such a fix is applied in vue?

Also, I managed to add a "$" sign for the pie values, how can I add thousand separators to it?

Thanks a lot for a magnificent work

**Comment by junedchhipa** [comment]
A fix in the core apexcharts.js library applies if the issue was in the core library.
You will need to update apexcharts when the new version is released by doing
```javascript
npm i --save apexcharts@latest
```
To format the labels for thousand separators is done the same way.
You will find answers to it in [StackOverflow](https://stackoverflow.com/questions/2901102/how-to-print-a-number-with-commas-as-thousands-separators-in-javascript).

Cheers!

**Comment by Amosss** [comment]
Thanks

**Comment by Amosss** [comment]
Apparently there is a way to get the same effect by using, for example:
```
total: {
   formatter: function (w) {
      return "$" + w.globals.seriesTotals.reduce((a, b) => {return a + b}, 0).toLocaleString();
   }
}
```
While the above works and the total is shown as 1,234.56
When hovering a slice, the total (of the slice) is shown as 1012.34 (the thousand separator disappears).

The above .toLocaleString() also works for labels of yaxis and donut labels.
