### ISSUE TITLE
Horizontal bar logarithmic yaxsis

### ISSUE THREAD

**Issue by cvakodobro** [apexcharts/vue-apexcharts#300]
# Bug report

## Codepen

https://codesandbox.io/s/vue-basic-example-forked-sm25o?file=/src/components/Chart.component.vue

## Explanation

_- What is the behavior you expect?_
Expected horizontal axis to be logarithmic

_- What is happening instead?_
Data is not shown, horizontal axis does not have logarithmic values

_- What error message are you getting?_
Error: Multiple Y Axis for bars are not supported. Switch to column chart by setting plotOptions.bar.horizontal=false

**Comment by meetakshiaggarwal** [comment]
I am getting the same issue for horizontal bar charts.
Since data is on xaxis - we might need an option to make xaxis logarithmic - or that yaxis logarithmic should work..(since ideally we are passing data into y axis). Anycase, this is an issue and needs to be resolved.
Please suggest a way to resolve this ?

**Comment by meetakshiaggarwal** [comment]
![image](https://user-images.githubusercontent.com/13766717/127147622-2fb508e4-4ecf-4ee5-a07f-54dad653aa19.png)
This is what i get if i set logarithmic true for yaxis.

**Comment by erick-tcsder** [comment]
same issue for me
