### ISSUE TITLE
CSV won't be generated if there are special characters on the series name

### ISSUE THREAD

**Issue by rafaoliverce** [apexcharts/vue-apexcharts#308]
I was working on a multi-series stacked chart and, for some reason, the CSV generated by the chart was returning empty, only the headers, no data.

The problem was the `name` of some series.
There were two series that contained names like `Series #1`.
After I removed the "#" character the CSV started working again as expected.

**Comment by sarahbeverton** [comment]
I'm having the same problem and really need the hashtag to still appear as the series title, as I am displaying twitter data based on hashtags. I am replacing the hashtags with &num; so that it still displays as a hashtag on the chart, but in the csv file it displays as &num; (but it at least shows the data - the data won't show up if there is a hashtag in the series title). Is there any other workaround for this or is this issue going to be fixed?
