### ISSUE TITLE
Deleting old values from an array change the entire graph in line chart

### ISSUE THREAD

**Issue by DrakoPOD** [apexcharts/vue-apexcharts#377]
I have a line chart that update every second, I have to deleted the old value after 60 seconds, because I have several graph I this may cause performance issues.

The problem is when I delete the first item `data.splice(0, 1);` the graph start moving like ocean waves. This doesn't show if I disable animations, but I want to keep animations. I think is because the `splice` function rearrange the entire array. Is there another way to delete old values.

```ts
    const data = reactive<Array<Array<number>>>([])
    const updateData = computed({
      get: () => data,
      set: (val: Array<number> | unknown | any) => { //Ignore this, is an error with TS
        data.push(val)
        if (data.length > 10){
          data.splice(0, 1);
          //delete data[0]
        }
      }
    })
//...
  const series = reactive([{
        name: 'series-1',
        data: updateData
      }])
```

**Comment by fabifink** [comment]
@DrakoPOD Just stumbled across the same issue. Have you found a solution to your problem?

**Comment by DrakoPOD** [comment]
@fabifink No, I just disable animations in pro of performance.

**Comment by ricky11** [comment]
had the same issue.

**Comment by ibrahim-007** [comment]
Maybe you would pop the previous data, like this "data.pop()"?

**Comment by ricky11** [comment]
> Maybe you would pop the previous data, like this "data.pop()"?

That would remove the most recent item , what we want to do is remove the oldest item and mutate the array itself, since we don't want to keep so much data.  

I find when i disable the animations, everything seems to work with .shift which removes the earliest element in the array./

`       if (series.value[0].data.length > 120) { // Keep only the last 120 data points
    series.value[0].data.shift()
}`

Have a  look at this video (the last 5 seconds will explain it.

When animations are turned off, there is no issue. 

https://github.com/apexcharts/vue-apexcharts/assets/5736415/c5fc7b6d-6f6f-4fd4-8c00-c4c86ed24e28

**Comment by ricky11** [comment]
I think the problem may be related to the d3 animation here, should be a an easy fix for someone who is familiar with  apex charts code base.

https://bost.ocks.org/mike/path/

**Comment by bradley-varol** [comment]
Experiencing this issue when limiting the size of a large dataset with animations enabled. It's a real shame as the animations look great. Anyone have any updates?
