### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by liron-navon** [apexcharts/vue-apexcharts#47]
When running in development/production mode with vue, I get no errors and the chars work as expected.
But when I try to test the component that is using the charts, it throws an exception:

I know it's a babel 7 issue, but this should be pretty simple to solve by replacing es5 modules (module.exports), with es6 modules (export default).

```
Cannot assign to read only property 'exports' of object '#<Object>'
```

**Comment by PisaJan** [comment]
Hey, we have encountered the same issue, could you please ping here when the svg.js version is bumped?

Thank you very much :)

**Comment by enrtama** [comment]
Same here, I see that svg.js is still version `^2.6.6`

**Comment by enrtama** [comment]
Hey! Any progress in updating this issue? Thanks!

**Comment by marianogoldman** [comment]
Stuck with the same here. Did you guys find any way to workaround it and be able to test your components in any way? Thanks.

**Comment by liron-navon** [comment]
wow that's old, I ended up abandoning apexcharts because of this

**Comment by mhgbrown** [comment]
Not sure if I encountered exactly the same situation as this, but I was getting the same error message as OP. I use `apexcharts` to create a library of custom chart types, which is then included in other projects. I fixed it by:
1. Telling `vue-cli` to transpile `apexcharts`
2. Downgrading `vue-apexcharts`

```javascript
// package.json
// note: at higher versions of vue-apexcharts, I get https://github.com/apexcharts/vue-apexcharts/issues/88
...
  "dependencies": {
    "apexcharts": "~3.14.0",
    ...
    "vue-apexcharts": "1.3.5",
    ...
  },
...

// babel.config.js
// ref: https://stackoverflow.com/questions/52615179/vue-cli-3-does-not-convert-vendors-to-es5
process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true

module.exports = {
  presets: [
    [
      '@vue/app'
    ]
  ]
}

// vue.config.js
module.exports = {
  transpileDependencies: ['apexcharts'],
  ...
}

**Comment by wmartins** [comment]
I don't know if anyone is still having problems with that. I've investigated a little more and I found out that the problem occurs because we're trying to `import` an `esm` module (in this case, this one: https://github.com/apexcharts/apexcharts.js/blob/dd24e9a8b01731d594dc656ff5fd987e2de574d4/dist/apexcharts.esm.js).

If you're using `vue-cli`, one way to solve this problem is to patch the module resolution and force to resolve to `commonjs` module. You can achieve that by changing your `vue.config.js`:

```js
module.exports = {
  /* ... */

  chainWebpack: config => {
    config.resolve.alias.set(
      'apexcharts$',
      'apexcharts/dist/apexcharts.common.js'
    )
  }

  /* ... */
}
```

I think there are other ways to do the same (I've seen some discussions about `esm` using webpack), however, I think this could be a fast way to solve this issue.
